# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hemma < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq), Caddy site blocks, and auth-provider config from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-hemma"
  version "0.29.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.0/hemma_0.29.0_darwin_amd64.tar.gz"
      sha256 "928f541820e5eeec5a925a251b44ff0043f254d4acf2c4c00bd7578dc6390adb"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.0/hemma_0.29.0_darwin_arm64.tar.gz"
      sha256 "2203a41d0a397582e62c659a2a87a4507f62aa892af74247186bb5c6405b525b"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.0/hemma_0.29.0_linux_amd64.tar.gz"
      sha256 "7c4cc66e8448c97409194e65aab05b3acf5bbe5db0117c2312eac327f565c12b"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.0/hemma_0.29.0_linux_arm64.tar.gz"
      sha256 "07c6a43516be2aa6f1a81a80c811085e3480cb83372f64fc8d261099de83645e"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  test do
    assert_match "hemma", shell_output("#{bin}/hemma version")
  end
end
