# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hemma < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq), Caddy site blocks, and auth-provider config from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-hemma"
  version "0.30.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.30.1/hemma_0.30.1_darwin_amd64.tar.gz"
      sha256 "56f355388a765987cf7057114b756df3029a1f0e7b4098908ea7e281cd614716"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.30.1/hemma_0.30.1_darwin_arm64.tar.gz"
      sha256 "12411fcd90bfd32a6c70e02c9d0358b1196f6c4251be3511ccfe688cfc848545"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.30.1/hemma_0.30.1_linux_amd64.tar.gz"
      sha256 "0574cee1a80d65402869db3cfd2035c41ee028b2274071a387d5d4336f6d6415"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.30.1/hemma_0.30.1_linux_arm64.tar.gz"
      sha256 "fdc2b73bd0b5229523c3bccc082458c0a214af7a8895cdaa55fd0ba47dfbc9ba"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  test do
    assert_match "hemma", shell_output("#{bin}/hemma version")
  end
end
