# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirage < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sd"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.10.0/mirage_0.10.0_darwin_amd64.tar.gz"
      sha256 "2c0bdc0523582725f0a97642202929cfcf679e9945b707ea06fcecf15f1a746d"

      define_method(:install) do
        bin.install "mirage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.10.0/mirage_0.10.0_darwin_arm64.tar.gz"
      sha256 "af93ad516f8424969d0bf46f8bbe9ad049a152e0dc93f491f5a967b4dd78d6d1"

      define_method(:install) do
        bin.install "mirage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.10.0/mirage_0.10.0_linux_amd64.tar.gz"
      sha256 "76e19c08238eded444cca02832620301749bea9e9cb44c5ba91a3a2fc99ec991"
      define_method(:install) do
        bin.install "mirage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.10.0/mirage_0.10.0_linux_arm64.tar.gz"
      sha256 "f711ffe17e08145a7695eb7da09c52d25d52df373e0862ccce3e7769969281a4"
      define_method(:install) do
        bin.install "mirage"
      end
    end
  end

  test do
    assert_match "mirage", shell_output("#{bin}/mirage version")
  end
end
