# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sd"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.1/sd_0.9.1_darwin_amd64.tar.gz"
      sha256 "0dab8562ac247c245cfa8261eb4d11fb5be4c0161800b42a6487a4f88852edec"

      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.1/sd_0.9.1_darwin_arm64.tar.gz"
      sha256 "2ee15b34a24388168ad25ec8c3502a1b9e9fecfad6387df18082b4bc94b21d20"

      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.1/sd_0.9.1_linux_amd64.tar.gz"
      sha256 "581b43e69b1a96ef32021ee85ed2f8138fd90739ddc71d8b45c651a784a5bc27"
      define_method(:install) do
        bin.install "sd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.9.1/sd_0.9.1_linux_arm64.tar.gz"
      sha256 "06da5b3e580317468b746be3352cddb3c9525675db91bb6cad4fb3f1dcf9d947"
      define_method(:install) do
        bin.install "sd"
      end
    end
  end

  test do
    assert_match "sd", shell_output("#{bin}/sd version")
  end
end
