# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-shd"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.0/shd_0.6.0_darwin_amd64.tar.gz"
      sha256 "040b5e0133efd0880da938bfe133b5173d7a91731621b5993bb51a2e576d97f7"

      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.0/shd_0.6.0_darwin_arm64.tar.gz"
      sha256 "420a1b2739f1fc1ec4b21da283e522dfa9e900bbd384fadcc6d168de24c03ba3"

      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.0/shd_0.6.0_linux_amd64.tar.gz"
      sha256 "0e2a8d75144f35b856e630ab0cc443d8fc89a37b99cb5004e6d01b546c8e5a93"
      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.6.0/shd_0.6.0_linux_arm64.tar.gz"
      sha256 "7049f543c96e60e0ed1ff892f41ea8d42a97c8b58583f69172b85b47a79a7e79"
      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  test do
    assert_match "shd", shell_output("#{bin}/shd version")
  end
end
