# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-shd"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.8.0/shd_0.8.0_darwin_amd64.tar.gz"
      sha256 "9d2772e43d6862ec39473eb18db51b205042e268a908ebb5f2df6ddb3ecc1304"

      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.8.0/shd_0.8.0_darwin_arm64.tar.gz"
      sha256 "2ed07884b997c62b3ab30cd2dac9545c0aad39ae4ba9562f205f62823ca67129"

      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.8.0/shd_0.8.0_linux_amd64.tar.gz"
      sha256 "4f6f8a56c00d60699e940f3b19dd9eb1a1aabb45d14317d72cf315395fd4a19f"
      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.8.0/shd_0.8.0_linux_arm64.tar.gz"
      sha256 "fcbe74991d39a0bb5b6962015dfe133df85e59c771d8d6ead5d9109010297fdd"
      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  test do
    assert_match "shd", shell_output("#{bin}/shd version")
  end
end
