# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitdns < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-splitdns"
  version "0.17.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.17.1/splitdns_0.17.1_darwin_amd64.tar.gz"
      sha256 "5ed89cb571ec932eed98fb482a0555765d24ef0caffc02b0d585d1ee50a017e7"

      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.17.1/splitdns_0.17.1_darwin_arm64.tar.gz"
      sha256 "7b8273ee875992f750f91dea94306479faada7b2b00e640f89c5eb243200320e"

      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.17.1/splitdns_0.17.1_linux_amd64.tar.gz"
      sha256 "3f0d9985a29ab84480a4f0b85a292baecc9c0a9e07ad07010e9448a368dee4fb"
      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.17.1/splitdns_0.17.1_linux_arm64.tar.gz"
      sha256 "cf3c2dfa428c6e7527193f42afca4e737425b62c5f8718d612b8a14152594bfd"
      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
  end

  test do
    assert_match "splitdns", shell_output("#{bin}/splitdns version")
  end
end
