# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitdns < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-splitdns"
  version "0.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.23.0/splitdns_0.23.0_darwin_amd64.tar.gz"
      sha256 "45f8432f7c704150b8bd8182aa9c551f6f3070652f6690cb24f9a0d579eeb4a8"

      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
        bash_completion.install "completions/splitdns.bash" => "splitdns"
        zsh_completion.install "completions/_splitdns.zsh" => "_splitdns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.23.0/splitdns_0.23.0_darwin_arm64.tar.gz"
      sha256 "f06e69d037121cd61cab50977ab5e36d685453ae2d55781b78255eaefadb406a"

      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
        bash_completion.install "completions/splitdns.bash" => "splitdns"
        zsh_completion.install "completions/_splitdns.zsh" => "_splitdns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.23.0/splitdns_0.23.0_linux_amd64.tar.gz"
      sha256 "03b79bf577fc4362b53744a4edb96d7ca27ccc34240682cb85517e10549e69c3"
      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
        bash_completion.install "completions/splitdns.bash" => "splitdns"
        zsh_completion.install "completions/_splitdns.zsh" => "_splitdns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.23.0/splitdns_0.23.0_linux_arm64.tar.gz"
      sha256 "0c1b2241ce69a6f325b63ebc972da5d19dbb86e91e18668e782e9373aad37ac6"
      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
        bash_completion.install "completions/splitdns.bash" => "splitdns"
        zsh_completion.install "completions/_splitdns.zsh" => "_splitdns"
      end
    end
  end

  test do
    assert_match "splitdns", shell_output("#{bin}/splitdns version")
  end
end
