// Package render produces the file contents for dnsmasq .conf and Caddy
// .caddy outputs (design §4).
package render

import "fmt"

// Header marks generated files. Identical across both output types.
const Header = "# GENERATED by shd — do not edit. Source: services.yaml"

// DNSRecord renders the dnsmasq address= directives for a service.
//
// The A record points at hostIP (the machine that RUNS the service), not the
// dns_host. The address=/<fqdn>/:: line is always emitted to suppress the
// public AAAA record; :: (unspecified) is correct, ::1 (loopback) is a bug
// (design §4.1).
func DNSRecord(fqdn, hostIP string) string {
	return fmt.Sprintf("%s\naddress=/%s/%s\naddress=/%s/::\n",
		Header, fqdn, hostIP, fqdn)
}

// CaddySite renders the Caddy site block for a service. tlsImport is the
// snippet name (e.g. tls_example_com); backend is emitted verbatim as the
// reverse_proxy upstream (design §4.2).
func CaddySite(fqdn, tlsImport, backend string) string {
	return fmt.Sprintf("%s\n%s {\n\timport %s\n\treverse_proxy %s\n}\n",
		Header, fqdn, tlsImport, backend)
}
