// Package render produces the file contents for dnsmasq .conf and Caddy
// .caddy outputs (design §4).
package render

import (
	"fmt"
	"strings"
)

// Header marks generated files. Identical across both output types.
const Header = "# GENERATED by sd — do not edit. Source: services.yaml"

// CaddyImportFile is the content of sd.generated.caddy — the single file
// every host's Caddyfile should import. Order matters: tls snippets must be
// defined before the site blocks that reference them.
const CaddyImportFile = Header + "\nimport tls/*.caddy\nimport sites/*.caddy\n"

// CaddyImportFilename is the name of the generated import file.
const CaddyImportFilename = "sd.generated.caddy"

// TLSSnippetName derives the Caddy snippet name for a domain: tls_ followed by
// the domain with dots replaced by underscores (e.g. example.com ->
// tls_example_com). Deterministic and collision-free across TLDs.
func TLSSnippetName(domain string) string {
	return "tls_" + strings.ReplaceAll(domain, ".", "_")
}

// TLSSnippet renders the Caddy (tls_<domain>) snippet that points at the
// domain's wildcard cert. The cert path convention is fixed:
// /etc/caddy/certs/<domain>/{fullchain.cer,privkey.key} (design §4.2). The
// tool generates this so a domain needs no hand-written Caddyfile snippet.
func TLSSnippet(domain string) string {
	return fmt.Sprintf(
		"%s\n(%s) {\n\ttls /etc/caddy/certs/%s/fullchain.cer /etc/caddy/certs/%s/privkey.key\n}\n",
		Header, TLSSnippetName(domain), domain, domain)
}

// DNSRecord renders the dnsmasq directives for a service.
//
//   - local=/<fqdn>/ makes dnsmasq authoritative for the WHOLE name, so query
//     types with no local record — notably the HTTPS/SVCB (type 65) record —
//     return NODATA instead of being forwarded upstream and cached. Required:
//     address= alone only covers A/AAAA; without local=, dnsmasq forwards the
//     HTTPS query to Cloudflare, and SVCB-aware clients (Safari, Chrome/Edge)
//     follow its public endpoint hint, bypassing split-horizon. (Verified: with
//     local= type 65 is NODATA; without it, type 65 is the cached Cloudflare
//     record.)
//   - the A record points at hostIP (the host that RUNS the service).
//   - address=/<fqdn>/:: suppresses the public AAAA; :: (unspecified) is
//     correct, ::1 (loopback) is a bug (design §4.1).
func DNSRecord(fqdn, hostIP string) string {
	return fmt.Sprintf("%s\nlocal=/%s/\naddress=/%s/%s\naddress=/%s/::\n",
		Header, fqdn, fqdn, hostIP, fqdn)
}

// CaddySite renders the Caddy site block for a service. tlsImport is the
// snippet name (e.g. tls_example_com); backend is emitted verbatim as the
// reverse_proxy upstream (design §4.2).
func CaddySite(fqdn, tlsImport, backend string) string {
	return fmt.Sprintf("%s\n%s {\n\timport %s\n\treverse_proxy %s\n}\n",
		Header, fqdn, tlsImport, backend)
}
