// Package render produces the file contents for dnsmasq .conf and Caddy
// .caddy outputs (design §4).
package render

import (
	"fmt"
	"strings"
)

// Header marks generated files. Identical across both output types.
const Header = "# GENERATED by shd — do not edit. Source: services.yaml"

// TLSSnippetName derives the Caddy snippet name for a domain: tls_ followed by
// the domain with dots replaced by underscores (e.g. example.com ->
// tls_example_com). Deterministic and collision-free across TLDs.
func TLSSnippetName(domain string) string {
	return "tls_" + strings.ReplaceAll(domain, ".", "_")
}

// TLSSnippet renders the Caddy (tls_<domain>) snippet that points at the
// domain's wildcard cert. The cert path convention is fixed:
// /etc/caddy/certs/<domain>/{fullchain.cer,privkey.key} (design §4.2). The
// tool generates this so a domain needs no hand-written Caddyfile snippet.
func TLSSnippet(domain string) string {
	return fmt.Sprintf(
		"%s\n(%s) {\n\ttls /etc/caddy/certs/%s/fullchain.cer /etc/caddy/certs/%s/privkey.key\n}\n",
		Header, TLSSnippetName(domain), domain, domain)
}

// DNSRecord renders the dnsmasq address= directives for a service.
//
// The A record points at hostIP (the host that RUNS the service), not the
// dns_host. The address=/<fqdn>/:: line is always emitted to suppress the
// public AAAA record; :: (unspecified) is correct, ::1 (loopback) is a bug
// (design §4.1).
func DNSRecord(fqdn, hostIP string) string {
	return fmt.Sprintf("%s\naddress=/%s/%s\naddress=/%s/::\n",
		Header, fqdn, hostIP, fqdn)
}

// CaddySite renders the Caddy site block for a service. tlsImport is the
// snippet name (e.g. tls_example_com); backend is emitted verbatim as the
// reverse_proxy upstream (design §4.2).
func CaddySite(fqdn, tlsImport, backend string) string {
	return fmt.Sprintf("%s\n%s {\n\timport %s\n\treverse_proxy %s\n}\n",
		Header, fqdn, tlsImport, backend)
}
